# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
# script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml

# Use postgresql instead of sqlite for database
recorder:
  db_url: !secret postgres_url
  auto_purge: true
  purge_keep_days: 14

influxdb:
  api_version: 2
  ssl: false
  host: !secret influx_ip
  port: !secret influx_port
  token: !secret influx_api_token
  organization: !secret influx_org
  bucket: homeassistant
  tags:
    source: ha
  tags_attributes:
    - friendly_name
  default_measurement: units
  include:
    domains:
      - sensor
      - climate

automation my_automations: !include_dir_merge_list automations/
automation remotes: !include_dir_merge_list remotes/
scene my_scenes: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/
input_boolean: !include_dir_merge_named input_booleans/

light lightgroups: !include_dir_merge_list lightgroups/

climate:
  - platform: generic_thermostat
    name: Bedroom Thermostat
    heater: switch.bedroom_space_heater
    target_sensor: sensor.bedroom_temperature
