- alias: basement_door_opens
  description: Lights on when basement door opens
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: off
    to: on
  condition: []
  action:
  - service: turn_on
    entity_id: light.basement_lights
    data:
      brightness: 100
  mode: single
